<title> Vyvy's vlog</title>
<h3> GitHub User </h3>
<h3> vtran10ocdsb.ca <h3>
 # this means to ignore newlines until "baseurl:"
  I'm new to coding, and I'm liking it. It'd very fun as well to learned.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
